/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TableFilterDemo;

import ConnectDB.ConnectDocGia;
import Origin.DocGia;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Toan Ho
 */
public class TestFiltering extends javax.swing.JFrame {

    /**
     * Creates new form TestFiltering
     */
    
    private ConnectDocGia connectDocGia = new ConnectDocGia();
    
    private TableRowSorter<TableModel> sorter;
    
    public TestFiltering() {
        initComponents();
        
        loadAllDocGia();
        
        filterTf.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                String text = filterTf.getText().trim();
                
                if (text.length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    try {
                        sorter.setRowFilter(RowFilter.regexFilter(text,1));
                    } catch (PatternSyntaxException psex) {
                        System.err.println("Bad regex pattern");
                    }
                }
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    private void loadAllDocGia() {
        DefaultTableModel model = new DefaultTableModel();
        
        ResultSet rs = connectDocGia.getData();
        try {
            // Load title for each column
            ResultSetMetaData rsMD = rs.getMetaData();
            
//            int colNum = rsMD.getColumnCount();
//            String[] arr = new String[colNum];
//            for (int i=0; i<colNum; i++) {
//                arr[i] = rsMD.getColumnName(i + 1);
//            }

            
            String[] arr = new String[2];
            arr[0] = rsMD.getColumnName(1);
            arr[1] = rsMD.getColumnName(4);
            
            model.setColumnIdentifiers(arr);
            
            // Load data to table
            while (rs.next()) {
                arr[0] = rs.getString(1);
                arr[1] = rs.getString(4);
                model.addRow(arr);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            System.err.println(ex.toString());
        }
        
        chooseDocGiaTable.setModel(model);
        sorter = new TableRowSorter<TableModel>(model);
        chooseDocGiaTable.setRowSorter(sorter);
        chooseDocGiaTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        chooseDocGiaTable.getColumnModel().getColumn(0).setMinWidth(80);
        chooseDocGiaTable.getColumnModel().getColumn(0).setMaxWidth(80);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filterTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        chooseDocGiaTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);
        jPanel1.add(filterTf);
        filterTf.setBounds(10, 11, 447, 20);

        jScrollPane1.setBackground(new java.awt.Color(102, 0, 51));

        chooseDocGiaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(chooseDocGiaTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 37, 447, 313);

        jButton1.setText("OK");
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 356, 447, 41);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TableFilterDemo/libraries.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFiltering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFiltering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFiltering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFiltering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFiltering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable chooseDocGiaTable;
    private javax.swing.JTextField filterTf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
